name: ops-ci
on:
  push: { branches: [main] }
  pull_request:

jobs:
  compose-smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cp .env.example .env
      - run: docker compose up -d
      - run: |
          timeout 90 bash -c 'until curl -sf http://localhost:8000/health; do sleep 3; done'
      - run: curl -sf http://localhost:8000/health
      - run: docker compose logs --no-color > compose.log || true
      - uses: actions/upload-artifact@v4
        with: { name: compose-logs, path: compose.log }
      - run: docker compose down -v
